const SET_INITIAL_LOADING_TO_FALSE = 'SET_INITIAL_LOADING_TO_FALSE';
const SET_TASKS = 'SET_TASKS';
const SET_TASKS_DONE = 'SET_TASKS_DONE';
const SET_TASKS_NOT_DONE = 'SET_TASKS_NOT_DONE';
const SET_LOADING = 'SET_LOADING';
const SET_LIGHT_THEME = 'SET_LIGHT_THEME';
const SET_DARK_THEME = 'SET_DARK_THEME';
const SET_PORTUGUESE_LANGUAGE = 'SET_PORTUGUESE_LANGUAGE';
const SET_ENGLISH_LANGUAGE = 'SET_ENGLISH_LANGUAGE';
const SET_SELECTED_TASK = 'SET_SELECTED_TASK';
const CLEAR_SELECTED_TASK = 'CLEAR_SELECTED_TASK';
const INCREASE_TASK_TIME_COUNTER = 'INCREASE_TASK_TIME_COUNTER';
const RESET_TASK_TIME_COUNTER = 'RESET_TASK_TIME_COUNTER';


export {
  SET_INITIAL_LOADING_TO_FALSE,
  SET_TASKS,
  SET_TASKS_DONE,
  SET_TASKS_NOT_DONE,
  SET_LOADING,
  SET_LIGHT_THEME,
  SET_DARK_THEME,
  SET_PORTUGUESE_LANGUAGE,
  SET_ENGLISH_LANGUAGE,
  SET_SELECTED_TASK,
  CLEAR_SELECTED_TASK,
  INCREASE_TASK_TIME_COUNTER,
  RESET_TASK_TIME_COUNTER,
};
